import:
  - https://raw.githubusercontent.com/Ensono/eirctl/refs/heads/main/shared/build/go/eirctl.yaml

contexts:
  unit:test:
    container:
      name: docker.io/dnitsch/aws-cli-auth-ci:0.2.0
      entrypoint: /usr/bin/env
      shell: sh
      shell_args:
        - -c
    envfile:
      exclude:
        - HOME
        - GO

pipelines:
  unit:test:run:
    - task: unit:test:prereqs
    - task: unit:test
      depends_on: unit:test:prereqs

tasks:
  unit:test:
    context: unit:test
    description: |
      Unit test runner needs a bit of extra care in this case to ensure we have all the dependencies
    command: |
      export GOPATH=$PWD/.deps GOBIN=$PWD/.deps/bin
      CGO_ENABLED=1 go test $(go list ./... | grep -v /local/) -v -coverpkg=./... -race -mod=readonly -timeout=1m -shuffle=on -buildvcs=false -coverprofile=.coverage/out -count=1 -run=$GO_TEST_RUN_ARGS | tee .coverage/test.out
      cat .coverage/test.out | .deps/bin/go-junit-report > .coverage/report-junit.xml
      .deps/bin/gocov convert .coverage/out | .deps/bin/gocov-xml > .coverage/report-cobertura.xml

  unit:test:prereqs:
    description: Installs coverage and junit tools
    context: unit:test
    command: 
      - |
        mkdir -p .coverage
        export GOPATH=$PWD/.deps GOBIN=$PWD/.deps/bin
        go install github.com/jstemmer/go-junit-report@v0.9.1
        go install github.com/axw/gocov/gocov@v1.0.0
        go install github.com/AlekSi/gocov-xml@v1.0.0
