FROM docker.io/golang:1.25.1-alpine3.21 AS golang

FROM docker.io/zenika/alpine-chrome:124

USER root

COPY --from=golang /usr/local/go /usr/local/go

ENV PATH=$PATH:/usr/local/go/bin

RUN apk add build-base
